version: '2'
services:
    timerecording-app:
        image: timerecording
        external_links:
            - timerecording-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/timerecording?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    timerecording-mysql:
        extends:
            file: mysql.yml
            service: timerecording-mysql
